apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-agent-golang
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: jenkins-agent-golang
    labels:
      app: jenkins-agent-golang
  spec:
    lookupPolicy:
      local: false
