apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: ODS_BITBUCKET_PROJECT
    description: Bitbucket project name.
    value: ${ODS_BITBUCKET_PROJECT}
  - name: PROJECT
    description: The name of the application project.
    required: true
  - name: BITBUCKET_URL
    description: The URL of your bitbucket server.
    required: true
  - name: CPU_LIMIT
    description: Maximum CPU available for the container.
    value: "1"
  - name: CPU_REQUEST
    description: Minimum CPU requested for the container.
    value: 100m
  - name: MEMORY_LIMIT
    description: Maximum amount of memory available for the container.
    value: 1024Mi
  - name: MEMORY_REQUEST
    description: Minimum amount of memory requested for the container.
    value: 512Mi
  - name: SERVICE_JVM_MEM_LIMIT
    description: Maximum amount of memory available for the DocGen Service, render process memory needs to be handled by MEMORY_LIMIT parameter
    value: 512m
  - name: SERVICE_JVM_ARGS
    description: JVM Tunning parameters for DocGen Service
    value: "-XX:+UseCompressedOops -XX:+UseG1GC -XX:MaxGCPauseMillis=1000"    
  - name: DOCKER_REGISTRY
    description: Image registry
    required: true
  - name: ODS_NAMESPACE
    description: Namespace where ODS is installed
    value: ods
  - name: ODS_IMAGE_TAG
    description: Image tag to use
    required: true
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        template: release-manager
      name: docgen
    spec:
      ports:
      -   name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: '${PROJECT}-docgen'
        deploymentconfig: docgen
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        template: release-manager
      name: 'docgen'
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: '${PROJECT}-docgen'
        deploymentconfig: 'docgen'
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: '${PROJECT}-docgen'
            deploymentconfig: 'docgen'
        spec:
          containers:
            - image: '${DOCKER_REGISTRY}/${ODS_NAMESPACE}/ods-doc-gen-svc:${ODS_IMAGE_TAG}'
              imagePullPolicy: IfNotPresent
              name: 'docgen'
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              env:
                - name: JAVA_MEM_XMX
                  value: '${SERVICE_JVM_MEM_LIMIT}'
                - name: JAVA_OPTS
                  value: '${SERVICE_JVM_ARGS}'
                - name: BITBUCKET_URL
                  value: '${BITBUCKET_URL}'
                - name: BITBUCKET_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: cd-user-with-password
                - name: BITBUCKET_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: cd-user-with-password
                - name: BITBUCKET_DOCUMENT_TEMPLATES_PROJECT
                  value: ${ODS_BITBUCKET_PROJECT}
                - name: BITBUCKET_DOCUMENT_TEMPLATES_REPO
                  value: ods-document-generation-templates
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
