apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.componentId }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.componentId }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
